/**
 * Internal jobs route — triggered by GitHub Actions cron workflows.
 *
 *   POST /api/jobs/refresh-mv   — refresh materialized views
 *
 * Protected by `JOBS_INTERNAL_TOKEN` bearer auth (auto-generated by Render,
 * mirrored as a GitHub Actions secret). This endpoint is NOT behind the
 * normal session/tenant/permission middleware — it's a machine-to-machine
 * call with its own shared-secret gate.
 */
import { Hono } from 'hono';
import { env } from '../../lib/env.js';
import { _refreshMatViewsOnce } from '../../lib/cron/refresh-mat-views.js';
import { logger } from '../../lib/logger.js';

export const jobsRoute = new Hono();

// ─── Token guard ───────────────────────────────────────────────────────────
// Every request to /api/jobs/* must carry a valid Bearer token.
jobsRoute.use('*', async (c, next) => {
  const token = env.JOBS_INTERNAL_TOKEN;
  if (!token) {
    logger.warn('JOBS_INTERNAL_TOKEN not set — rejecting jobs request');
    return c.json({ error: 'jobs_not_configured' }, 503);
  }

  const authHeader = c.req.header('authorization');
  if (!authHeader || authHeader !== `Bearer ${token}`) {
    return c.json({ error: 'unauthorized' }, 401);
  }

  await next();
  return undefined;
});

// ─── POST /refresh-mv ──────────────────────────────────────────────────────
jobsRoute.post('/refresh-mv', async (c) => {
  try {
    const result = await _refreshMatViewsOnce();
    logger.info({ ...result }, 'manual mat-view refresh via jobs endpoint');
    return c.json({ ok: true, ...result });
  } catch (err) {
    logger.error({ err }, 'mat-view refresh via jobs endpoint failed');
    const message = err instanceof Error ? err.message : String(err);
    return c.json({ error: 'refresh_failed', detail: message }, 500);
  }
});
